language: go

env:
  - GO111MODULE: on

install: 
  - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
  - unzip terraform.zip
  - go get github.com/mercari/tfnotify

script:
  - ./terraform init
  - ./terraform plan | tfnotify plan
